let profile = [
  {
    "kod": 2224,
    "opis": "Prowadnica 2224",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 6.73,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 2304,
    "opis": "Łącznik kątowy 2304",
    "makro": "nie",
    "typ": "1K1",
    "cenab": "",
    "cena1k": 8.29,
    "cena2k": null,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 2311,
    "opis": "Poszerzenie 2311",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 8.3,
    "cena2k": 10.35,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 2313,
    "opis": "Poszerzenie 2313",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.71,
    "cena2k": 4.67,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 2315,
    "opis": "Poszerzenie 2315",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 2.96,
    "cena2k": 3.64,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 3195,
    "opis": "Szpros 3195",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 3.72,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 3196,
    "opis": "Szpros 3196 23 mm",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 3,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 3284,
    "opis": "Łącznik H 3284 dwurzędowy",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.48,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 3292,
    "opis": "Zaślepka 3292",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.31,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 3314,
    "opis": "[GEALAN] 3314 część monostulpu",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 3.29,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 3325,
    "opis": "Okapnik 3325",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.93,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 3326,
    "opis": "Okapnik 3326",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.45,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 5148,
    "opis": "Listwa 5148",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.7,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5201,
    "opis": "Poszerzenie 5201",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.76,
    "cena2k": 4.44,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5201,
    "opis": "Poszerzenie 5201",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.76,
    "cena2k": 4.44,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5202,
    "opis": "Poszerzenie 5202",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.91,
    "cena2k": 6.03,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5202,
    "opis": "Poszerzenie 5202",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.91,
    "cena2k": 6.03,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5203,
    "opis": "Poszerzenie 5203",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 9.73,
    "cena2k": 12.11,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5203,
    "opis": "Poszerzenie 5203",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 9.73,
    "cena2k": 12.11,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5204,
    "opis": "Łącznik statyczny 5204",
    "makro": "nie",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 5.07,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 5206,
    "opis": "Łącznik 5206",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 9.33,
    "cena2k": 11.82,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5207,
    "opis": "Łącznik 5207",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.84,
    "cena2k": 5.91,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5213,
    "opis": "Poszerzenie 5213",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 5.16,
    "cena2k": 6.47,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5524,
    "opis": "Listwa 5524",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.99,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5525,
    "opis": "Listwa 5525",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 3.36,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 5526,
    "opis": "Listwa 5526",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 3.2,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  // {
  //   "kod": 5860,
  //   "opis": "Ościeżnica 5860 74/150 mm #5#",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 10.29,
  //   "cena2k": 11.57,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 5861,
  //   "opis": "Profil maskujący Smoovio 8 / 63 mm",
  //   "makro": "tak",
  //   "typ": "1K2",
  //   "cenab": "",
  //   "cena1k": null,
  //   "cena2k": 3.52,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 5862,
  //   "opis": "Skrzydło 5862 92/74 mm",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 8.55,
  //   "cena2k": 9.56,
  //   "uszczelkabiale": "",
  //   "uszczelka": "Q"
  // },
  // {
  //   "kod": 5863,
  //   "opis": "Profil do szklenia stałego 5863 59,5/74 mm",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 7.15,
  //   "cena2k": 7.62,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 5868,
  //   "opis": "Profil labiryntowy 14/31 mm",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 2.66,
  //   "cena2k": 3.29,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 5869,
  //   "opis": "Profil wyrównujący SMOOVIO 19,5 / 57 mm",
  //   "makro": "tak",
  //   "typ": "1K1",
  //   "cenab": "",
  //   "cena1k": 4.05,
  //   "cena2k": null,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  {
    "kod": 6001,
    "opis": "Ościeżnica do fixów",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.74,
    "cena2k": 4.78,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6002,
    "opis": "Ościeżnica 6002",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.93,
    "cena2k": 4.96,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6003,
    "opis": "Skrzydło 6003",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.93,
    "cena2k": 4.96,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6004,
    "opis": "Ościeżnica 6004",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.93,
    "cena2k": 4.96,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6009,
    "opis": "Ościeżnica 6009",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 5.62,
    "cena2k": 6.59,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6012,
    "opis": "Słupek ruchomy",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 5.08,
    "cena2k": 6.12,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6015,
    "opis": "Ościeżnica do fixów",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.62,
    "cena2k": 5.65,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6017,
    "opis": "Skrzydło 6017",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 7.05,
    "cena2k": 8.08,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6023,
    "opis": "Skrzydło 6023",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.49,
    "cena2k": 5.65,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6025,
    "opis": "Skrzydło 6025",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 7.5,
    "cena2k": 8.9,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6026,
    "opis": "Ościeżnica 6026",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 6,
    "cena2k": 7.82,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6027,
    "opis": "Skrzydło 6027",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 7.73,
    "cena2k": 9,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6030,
    "opis": "Ościeżnica 6030 renowacje",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 5.63,
    "cena2k": 7.45,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6033,
    "opis": "Skrzydło 6033",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 7.73,
    "cena2k": 8.9,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6039,
    "opis": "Skrzydło 6039",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 9.35,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6049,
    "opis": "Słupek stały - 6049",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.73,
    "cena2k": 5.78,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6050,
    "opis": "Słupek",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.96,
    "cena2k": 6,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6053,
    "opis": "Słupek stały 6053",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 8.65,
    "cena2k": 9.83,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6054,
    "opis": "Słupek 6054",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 9.2,
    "cena2k": 10.39,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6055,
    "opis": "Skrzydło 6055",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.93,
    "cena2k": 4.96,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6057,
    "opis": "Słupek 6057",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.96,
    "cena2k": 6,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6058,
    "opis": "Słupek 6058",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 9.92,
    "cena2k": 11.38,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6059,
    "opis": "Monostulp 6059",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.85,
    "cena2k": 6,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6079,
    "opis": "Skrzydło 6079",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 3.62,
    "cena2k": 4.73,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6124,
    "opis": "Listwa 6124",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.68,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 6126,
    "opis": "Listwa 6126",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.11,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 6128,
    "opis": "Listwa 6128",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.09,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 6130,
    "opis": "Listwa 6130",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.09,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 6132,
    "opis": "Listwa 6132",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.09,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6134,
    "opis": "Listwa 6134",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.09,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6136,
    "opis": "Listwa 6136",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.55,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6138,
    "opis": "Listwa 6138",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.01,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6140,
    "opis": "Listwa 6140",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.5,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6142,
    "opis": "Listwa 6142",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.01,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6144,
    "opis": "Listwa 6144",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.79,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6146,
    "opis": "Listwa 6146",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.77,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6148,
    "opis": "Listwa 6148",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.5,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6150,
    "opis": "Listwa 6150",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.95,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6152,
    "opis": "Listwa 6152",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.95,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 6301,
    "opis": "Część monostulpu 6301",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.38,
    "cena2k": 4.38,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  {
    "kod": 6802,
    "opis": "Ościeżnica NL",
    "makro": "tak",
    "typ": "2K",
    "cenab": "",
    "cena1k": 14,
    "cena2k": 13.13,
    "uszczelkabiale": "",
    "uszczelka": "Q"
  },
  // {
  //   "kod": 7001,
  //   "opis": "Ościeżnica 7001",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 2.98,
  //   "cena2k": 3.91,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 7040,
  //   "opis": "Słupek 7040",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 4.81,
  //   "cena2k": 5.8,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 7060,
  //   "opis": "Słupek ruchomy 7060",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 4.56,
  //   "cena2k": 5.48,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 7072,
  //   "opis": "Skrzydło 7072",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 2.79,
  //   "cena2k": 3.72,
  //   "uszczelkabiale": "",
  //   "uszczelka": "Q"
  // },
  {
    "kod": 7116,
    "opis": "Listwa 7116",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.73,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7119,
    "opis": "Listwa 7119",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.88,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7120,
    "opis": "Listwa 7120",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.53,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7122,
    "opis": "Listwa 7122",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.72,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7129,
    "opis": "Listwa 7129",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.96,
    "uszczelkabiale": "00G",
    "uszczelka": "S"
  },
  {
    "kod": 7130,
    "opis": "Listwa 7130",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.55,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7131,
    "opis": "Listwa 7131",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.28,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7134,
    "opis": "Listwa 7134",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.46,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7138,
    "opis": "Listwa 7138",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.79,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7139,
    "opis": "Listwa 7139",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 3.19,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7142,
    "opis": "Listwa 7164",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.74,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7144,
    "opis": "Listwa 7144",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.9,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7146,
    "opis": "Listwa 7146",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.78,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7154,
    "opis": "Listwa 7154",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.46,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7156,
    "opis": "Listwa 7156",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.28,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7162,
    "opis": "Listwa 7162",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.5,
    "uszczelkabiale": "",
    "uszczelka": "S"
  },
  {
    "kod": 7164,
    "opis": "Listwa 7164",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.54,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7180,
    "opis": "Listwa 7180",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.77,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7194,
    "opis": "Listwa 7194",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.68,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7196,
    "opis": "Listwa 7196",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.92,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7222,
    "opis": "Listwa 7222",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 2.46,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7224,
    "opis": "Listwa 7224",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.34,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7226,
    "opis": "Listwa 7226",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.15,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7228,
    "opis": "Listwa 7228",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.54,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7236,
    "opis": "Listwa 7236",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.52,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7242,
    "opis": "Listwa 7242",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.88,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7248,
    "opis": "Listwa 7248",
    "makro": "tak",
    "typ": "1K2",
    "cenab": "",
    "cena1k": null,
    "cena2k": 1.21,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  {
    "kod": 7292,
    "opis": "Poszerzenie 7292",
    "makro": "nie",
    "typ": "2K",
    "cenab": "",
    "cena1k": 4.9,
    "cena2k": 6.14,
    "uszczelkabiale": "",
    "uszczelka": ""
  },
  // {
  //   "kod": 8001,
  //   "opis": "Profil 8001 RAMA 66 MM 6K",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 2.73,
  //   "cena2k": 3.62,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8006,
  //   "opis": "Profil 8006 RAMA 66 MM 5K",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 4.28,
  //   "cena2k": 5.48,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8010,
  //   "opis": "Profil 8010 RAMA 74 MM 6K",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 7.79,
  //   "cena2k": 8.69,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8012,
  //   "opis": "Profil 8012 RAMA 81 MM 5K",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 5.7,
  //   "cena2k": 7.46,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8014,
  //   "opis": "Profil 8014 RAMA 96 MM",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 10.23,
  //   "cena2k": 12.02,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8033,
  //   "opis": "Profil 8033 RAMA RENOWACYJNA 101 MM",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 7.41,
  //   "cena2k": 8.8,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8034,
  //   "opis": "Profil 8034 RAMA RENOWACYJNA 113 MM",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 6.72,
  //   "cena2k": 9.67,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  // {
  //   "kod": 8036,
  //   "opis": "Profil 8036 SZPROS 66 MM",
  //   "makro": "tak",
  //   "typ": "2K",
  //   "cenab": "",
  //   "cena1k": 6,
  //   "cena2k": 7.41,
  //   "uszczelkabiale": "",
  //   "uszczelka": ""
  // },
  {
    kod: 3261,
    opis: "Listwa 3261",
    makro: "nie",
    typ: "1K1",
    cenab: 0.75,
    cena1k: 1.46,
    uszczelkabiale: '',
    uszczelka: ' '
  },
  {
    kod: 3205,
    opis: "Profil maskujący 3205",
    makro: "nie",
    typ: "1K2",
    cenab: 2.19,
    cena2k: 3.97,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 3206,
    opis: "Profil maskujący 3206",
    makro: "nie",
    typ: "1K2",
    cenab: 1.84,
    cena2k: 3.59,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 3208,
    opis: "Profil maskujący 3208",
    makro: "nie",
    typ: "1K2",
    cenab: 1.77,
    cena2k: 3.78,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 3216,
    opis: "Profil maskujący 3216",
    makro: "nie",
    typ: "1K2",
    cenab: 1.83,
    cena2k: 3.03,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 3217,
    opis: "Profil maskujący 3217",
    makro: "nie",
    typ: "1K2",
    cenab: 1.65,
    cena2k: 2.09,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 7281,
    opis: "Łącznik 7281",
    makro: "nie",
    typ: "1K2",
    cenab: 3.85,
    // cena1k: 4.9,
    cena2k: 9.26,
    uszczelkabiale: "00",
    pokurwioneantracyty: false,
    uszczelka: " ",
  },
  {
    kod: 3348,
    opis: "Prowadnica 3348 41/50mm",
    makro: "nie",
    typ: "1K2",
    cenab: 2.5,
    cena1k: null,
    cena2k: 5.71,
    uszczelkabiale: "00",
    uszczelka: "S",
  },
  {
    kod: 6034,
    opis: "Poszerzenie drzwi 6034",
    makro: "nie",
    typ: "2K",
    cenab: 8.74,
    cena1k: 10.24,
    cena2k: 12.1,
    uszczelkabiale: "00U",
    uszczelka: "S",
  },
  {
    kod: 7001,
    opis: "Ościeżnica 7001",
    makro: "nie",
    typ: "2K",
    cenab: 2.25,
    cena1k: 3.19,
    cena2k: 4.18,
    uszczelkabiale: "88U",
    uszczelka: "S",
  },
  {
    kod: 7072,
    opis: "Skrzydło 7072",
    makro: "nie",
    typ: "2K",
    cenab: 2.05,
    cena1k: 2.99,
    cena2k: 3.98,
    uszczelkabiale: "88U",
    uszczelka: "S",
  },
  {
    kod: 8092,
    opis: "Skrzydło 8092",
    makro: "nie",
    typ: "2K",
    cenab: 2.97,
    cena1k: 3,
    cena2k: 3.95,
    uszczelkabiale: "88U",
    uszczelka: "Q",
  },
  {
    kod: 8042,
    opis: "Skrzydło 8042",
    makro: "nie",
    typ: "2K",
    cenab: 9.34,
    cena1k: 12.26,
    cena2k: 13.91,
    uszczelkabiale: "88U",
    uszczelka: "Q",
  },
  {
    kod: 8076,
    opis: "Skrzydło 8076",
    makro: "nie",
    typ: "2K",
    cenab: 7.86,
    cena1k: 11.98,
    cena2k: 14.18,
    uszczelkabiale: "88U",
    uszczelka: "Q",
  },
  {
    kod: 8081,
    opis: "Skrzydło 8081",
    makro: "nie",
    typ: "2K",
    cenab: 5.55,
    cena1k: 7.09,
    cena2k: 8.32,
    uszczelkabiale: "88U",
    uszczelka: "Q",
  },
  {
    kod: 3210,
    opis: "Profil podparapetowy 3210",
    makro: "nie",
    typ: "1K2",
    cenab: 2.27,
    // cena1k: 12.26,
    cena2k: 3.95,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 2267,
    opis: "Profil podparapetowy 2267",
    makro: "nie",
    typ: "1K2",
    cenab: 2.27,
    // cena1k: 12.26,
    cena2k: 3.95,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 2257,
    opis: "Listwa kryjąca",
    makro: "nie",
    typ: "1K2",
    cenab: 1.27,
    // cena1k: 12.26,
    cena2k: 1.23,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 8043,
    opis: "Słupek 8043",
    makro: "nie",
    typ: "2K",
    cenab: 8.08,
    cena1k: 12.78,
    cena2k: 13.8,
    uszczelkabiale: "00",
    uszczelka: "S",
  },
  {
    kod: 8040,
    opis: "Słupek 8040",
    makro: "nie",
    typ: "2K",
    cenab: 3.39,
    cena1k: 5.04,
    cena2k: 6.4,
    uszczelkabiale: "00G",
    uszczelka: "S",
  },
  {
    kod: 7291,
    opis: "Profil statyczny 7291",
    makro: "nie",
    typ: "1K2",
    cenab: 3.88,
    // cena1k: 9.37,
    cena2k: 6.05,
    uszczelkabiale: "00",
    uszczelka: " ",
  },
  {
    kod: 2233,
    opis: "Łącznik rurowy 2233",
    makro: "nie",
    typ: "2K",
    cenab: 7.88,
    cena1k: 10.03,
    cena2k: 12.87,
    uszczelkabiale: "00S",
    uszczelka: "S",
  }
]

export default profile;